### ISSUE TITLE
Ensure the Azure remedy controller is used by the landscape integration tests

### ISSUE THREAD

**Issue by stoyanr** [gardener/remedy-controller#10]
Once https://github.com/gardener/gardener-extension-provider-azure/pull/120 is merged and a release containing it is used by the landscape setup, we should also ensure that the Azure remedy controller is used by the landscape integration tests:

* Azure shoots created as part of these integration tests are annotated with `azure.provider.extensions.gardener.cloud/enable-remedy-controller: "true"` so that they get the remedy controller.
* Perhaps we should also extend the tests to (partially) test the functionality of the remedy controller itself (?)

**Comment by AndreasBurger** [comment]
The remedy controller is being deployed for the landscape integration tests on Azure as of about two weeks ago. Closing this.
