### ISSUE TITLE
Shoot could not be deleted due to a PublicIPAddress resource that can't be deleted

### ISSUE THREAD

**Issue by stoyanr** [gardener/remedy-controller#32]
**What happened**:
During landscape integration tests, a few times the shoot could not be deleted because the shoot namespace in the seed contains a `PublicIPAddress` resource for the nginx addon service that can't be deleted due to having a finalizer, but the remedy controller that should remove this finalizer is already gone.
The issue occurred on 15.07 with the cluster https://dashboard.garden.staging.k8s.ondemand.com/namespace/garden-it/shoots/tmyvi-1mv/ (already deleted).

**What you expected to happen**:
Shoot deletion should always succeed. The finalizer from all `PublicIPAddress` resources should be removed by the remedy controller before it is deleted itself.

**How to reproduce it (as minimally and precisely as possible)**:
It seems to be very hard to reproduce this issue manually. I tried it several times but never succeeded. In the Gardener code, there is a forced 5 min wait between the step that deletes the managed resources (and therefore all services except `allow-udp-egress`) and the step that deletes the controlplane (and therefore the remedy controller). In my tests, all services and their `PublicIPAddress` resources were always deleted a few minutes before this wait finished, and therefore the cluster deletion finished without any issues.

**Anything else we need to know**:
I believe the issue should only be reproducible if there are actual issues with Azure that prevent the normal handling of IP addresses. We would need additional information, such as how many times was this issue reproduced, when was the last time it was reproduced, etc. Perhaps we should wait for another failed deletion, in order to investigate.

**Environment**:

**Comment by stoyanr** [comment]
@dguendisch Could you please provide any additional information you have about this issue, such as how many times was this issue reproduced, when was the last time it was reproduced, etc.

**Comment by stoyanr** [comment]
This is the `PublicIPAddress` resource that had to be deleted manually by @AndreasBurger in the above cluster:
```yaml
apiVersion: azure.remedy.gardener.cloud/v1alpha1
kind: PublicIPAddress
metadata:
  creationTimestamp: "2020-07-14T15:27:51Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2020-07-14T16:57:22Z"
  finalizers:
  - azure.remedy.gardener.cloud/publicipaddress
  generation: 2
  labels:
    azure.remedy.gardener.cloud/service: kube-system.addons-nginx-ingress-controller
  name: kube-system-addons-nginx-ingress-controller-40.127.238.116
  namespace: shoot--it--tmyvi-1mv
  resourceVersion: "1097257636"
  selfLink: /apis/azure.remedy.gardener.cloud/v1alpha1/namespaces/shoot--it--tmyvi-1mv/publicipaddresses/kube-system-addons-nginx-ingress-controller-40.127.238.116
  uid: ca50fd2c-6c6b-47ab-8b50-2e21aacf41bc
spec:
  ipAddress: 40.127.238.116
status:
  exists: false
```

**Comment by dguendisch** [comment]
> @dguendisch Could you please provide any additional information you have about this issue, such as how many times was this issue reproduced, when was the last time it was reproduced, etc.

Not much to add: about two times the week before last week, about once in the last week. I haven't kept track of when exactly it happened, it's somehow rare but still occurred.
I can notify you and @AndreasBurger as soon as it occurs again.

**Comment by stoyanr** [comment]
The issue was reproduced yesterday on one of our canary clusters. Unfortunately all remedy controller logs are already gone. It seems that the 2 `PublicIPAddress` resources were never deleted for some reason, since their deletion timestamps are later than the deletion timestamp of the namespace itself, so only got deleted at the very end, once the namespace itself was deleted. It's very hard to understand however what might cause such behavior.
After discussing with @rfranzke, we figured out that one possible way to address this issue would be to to change the Azure controlplane controller so that it checks if it’s safe to delete the controller and only do it if it is. This should also help us to debug this situation if it happens again.
